[lief.build]
type            = "Release"
cache           = true
ninja           = true
parallel-jobs   = 0
lief-install-dir = "~/lief-x64-install"
extra-cmake-opt = [
  "-DCMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded",
]

[lief.formats]
elf     = true
pe      = true
macho   = true
android = true
art     = true
vdex    = true
oat     = true
dex     = true

[lief.features]
json    = true
frozen  = true

[lief.logging]
enabled = true
debug   = false
