[lief.s3]
region = "fr-par"
bucket = "lief"
endpoint = "https://s3.fr-par.scw.cloud"

[lief.deploy]
branches = ["main", "master", "deploy", "devel"]
main-branches = ["main", "master"]
default-dir = "latest"
