[lief.build]
type             = "Release"
cache            = true
ninja            = true
parallel-jobs    = 0
cxx-compiler     = "clang++"
c-compiler       = "clang"
lief-install-dir = "{ci_project_dir}/lief-static-install/"
extra-cmake-opt  = [
  "--toolchain /cmake/linux/linux-glibc28.cmake",
  "-DPython_VERSION={python_version}",
  "-DCMAKE_COLOR_DIAGNOSTICS=ON",
  "-DCMAKE_CXX_COMPILER=clang++",
  "-DCMAKE_C_COMPILER=clang",
  "-DCMAKE_MODULE_PATH=/cmake/linux/",
]

[lief.formats]
elf     = true
pe      = true
macho   = true
android = true
art     = true
vdex    = true
oat     = true
dex     = true

[lief.features]
json    = true
frozen  = true

[lief.logging]
enabled = true
debug   = false

[lief.cross-compilation]
platform  = "manylinux_2_28_x86_64"
pyversion = "cp{python_version_alt}"
abi       = "cp{python_version_alt}"
